name: Add Numbers and Save to Excel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  add-numbers-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Perform addition and save to file
        run: |
          num1=10
          num2=20
          result=$((num1 + num2))
          
          # Print the result
          echo "Result of $num1 + $num2 = $result"
          
          # Save result to a file (Excel simulation)
          echo "Number 1, Number 2, Result" > output.csv
          echo "$num1, $num2, $result" >> output.csv
          
          echo "Result saved to output.csv"
